### ISSUE TITLE
replicating readme on Windows

### ISSUE THREAD

**Issue by joshualerickson** [JosiahParry/rsgeo#3]
Hey @JosiahParry, great stuff as usual. All this above my head but thought I'd give a shot and run through the readme. Ran into some errors trying to reproduce and seems to be with a few functions: `closest_point()`, `haversine_destination()` ,  `haversine_intermediate()`, and a `plot()` method with `rs_polys[[1]]`. 

**update** 

Went back and ran the  `plot(x)` and `plot(x_simple, add = TRUE)` with `Error in geom_to_r(x) : object 'wrap__geom_to_r' not found` and only works with `plot(rs_polys[37])` instead of `plot(rs_polys[[37]]`; however, you still get an error with `x_simple` regardless of how you index `rs_polys`.

<details>
<summary>version</summary>

```
$platform
[1] "x86_64-w64-mingw32"

$arch
[1] "x86_64"

$os
[1] "mingw32"

$crt
[1] "ucrt"

$system
[1] "x86_64, mingw32"

$status
[1] ""

$major
[1] "4"

$minor
[1] "2.2"

$year
[1] "2022"

$month
[1] "10"

$day
[1] "31"

$`svn rev`
[1] "83211"

$language
[1] "R"

$version.string
[1] "R version 4.2.2 (2022-10-31 ucrt)"

$nickname
[1] "Innocent and Trusting"
```
</details>

I'll be referring to the lines in the readme and associated errors. If I don't mention a line it means that it ran without error.  

**Lines 95-100**  

errors on both `plot(x)` and `plot(x_simple, add = TRUE)` with `Error in geom_to_r(x) : object 'wrap__geom_to_r' not found`

**Lines 121-127**

error with `closest_point()` `Error in closest_point(rs_polys[[1]], geom_point(8e+05, 2090000)) : 
  closest_point panicked.`

Then same  'wrap__geom_to_r' not found` with `plot(rs_polys([[1]])` and can't plot `close_pnt` bc not successful.

**Lines 133-137**

`haversine_destination()` function errored `Error in haversine_destination(geom_point(10, 10), 45, 10000) : 
  haversine_destination panicked.`

`geosphere::destPoint()` worked

**Line 144**

Same as above with `haversine_destination()`

**Lines 153-164**

Same as above but with `haversine_intermediate()` and  error with `plot(chaikin_smoothing(region,5))` with `Error in geom_to_r(x) : object 'wrap__geom_to_r' not found`

**Comment by Robinlovelace** [comment]
I can try reproducing this on work laptop if that would help.

**Comment by JosiahParry** [comment]
Thank you! I can reproduce :)
