### ISSUE TITLE
Set minimum R version to 4.4.0

### ISSUE THREAD

**Issue by Robinlovelace** [JosiahParry/rsgeo#46]

**Comment by JosiahParry** [comment]
The minimum version required to use the latest version of {rsgeo} is not 4.4.0. Here is me installing it with 4.3.3

![Screen Recording 2024-07-24 at 17 42 42](https://github.com/user-attachments/assets/e5d3c013-7ae3-410d-b6a0-269135e9c115)

**Comment by Robinlovelace** [comment]
OK fair.
